//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivo
    {
        public int ID { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public string Nome { get; set; }
        public byte[] AnexoBytes { get; set; }
        public string AnexoExtensao { get; set; }
        public string AnexoTipo { get; set; }
    
        public virtual Produtos Produtos { get; set; }
    }
}
