//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JC_BookStation.Data.MetaData;

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(CompraMetadata))]
    public partial class Compra
    {
        public Compra()
        {
            this.Financeiro = new HashSet<Financeiro>();
            this.ProdutosCompra = new HashSet<ProdutosCompra>();
        }
    
        public int IdCompra { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
        public string CodigoNota { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<System.DateTime> DataCompra { get; set; }
        public string Obs { get; set; }
        public Nullable<int> Parcelas { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual ICollection<Financeiro> Financeiro { get; set; }
        public virtual ICollection<ProdutosCompra> ProdutosCompra { get; set; }
    }
}
