//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMenu
    {
        public int Id { get; set; }
        public Nullable<int> Usuario { get; set; }
        public string Menu { get; set; }
        public Nullable<int> Bloqueado { get; set; }
    }
}
