//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arquivo> Arquivo { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Comissao> Comissao { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<ConfigMenu> ConfigMenu { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Financeiro> Financeiro { get; set; }
        public virtual DbSet<FinanceiroTipo> FinanceiroTipo { get; set; }
        public virtual DbSet<Fornecedores> Fornecedores { get; set; }
        public virtual DbSet<Funcao> Funcao { get; set; }
        public virtual DbSet<Funcionarios> Funcionarios { get; set; }
        public virtual DbSet<GrupoClientes> GrupoClientes { get; set; }
        public virtual DbSet<GrupoProdutos> GrupoProdutos { get; set; }
        public virtual DbSet<Loja> Loja { get; set; }
        public virtual DbSet<Orcamentos> Orcamentos { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Produtos> Produtos { get; set; }
        public virtual DbSet<ProdutosCompra> ProdutosCompra { get; set; }
        public virtual DbSet<ProdutosOrcamento> ProdutosOrcamento { get; set; }
        public virtual DbSet<ProdutosVenda> ProdutosVenda { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venda> Venda { get; set; }
        public virtual DbSet<NotaPromissoria> NotaPromissoria { get; set; }
    }
}
