//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JC_BookStation.Data.MetaData;

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(FornecedorMetadata))]
    public partial class Fornecedores
    {
        public Fornecedores()
        {
            this.Compra = new HashSet<Compra>();
            this.Produtos = new HashSet<Produtos>();
        }
    
        public int IdFornecedor { get; set; }
        public string Nome { get; set; }
        public string CEP { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public Nullable<short> Cidade { get; set; }
        public Nullable<short> Estado { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Contato { get; set; }
        public string Celular { get; set; }
        public string RGIE { get; set; }
    
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual ICollection<Produtos> Produtos { get; set; }
    }
}
