//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcao
    {
        public Funcao()
        {
            this.Funcionarios = new HashSet<Funcionarios>();
        }
    
        public int IdFuncao { get; set; }
        public string NomeFuncao { get; set; }
        public Nullable<int> Ativo { get; set; }
        public Nullable<int> Ordem { get; set; }
    
        public virtual ICollection<Funcionarios> Funcionarios { get; set; }
    }
}
