//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JC_BookStation.Data.MetaData;

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(LojaMetadata))]
    public partial class Loja
    {
        public Loja()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdLoja { get; set; }
        public string CNPJ { get; set; }
        public string CPF { get; set; }
        public string RazaoSocial { get; set; }
        public string Fantasia { get; set; }
        public string NomeContato { get; set; }
        public string CEP { get; set; }
        public string Logradouro { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Bairro { get; set; }
        public Nullable<short> Cidade { get; set; }
        public Nullable<short> Estado { get; set; }
        public string CaminhoLogo { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public bool ATIVO { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
