//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JC_BookStation.Data.MetaData;

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(NotaPromissoriaMetadata))]
    public partial class NotaPromissoria
    {
        public int IdNota { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVenda { get; set; }
        public Nullable<int> Parcela { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Status { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
