//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using JC_BookStation.Data.MetaData;

namespace JC_BookStation.Data.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(VendaMetadata))]
    public partial class Venda
    {
        public Venda()
        {
            this.Comissao = new HashSet<Comissao>();
            this.Financeiro = new HashSet<Financeiro>();
            this.ProdutosVenda = new HashSet<ProdutosVenda>();
            this.NotaPromissoria = new HashSet<NotaPromissoria>();
        }

        public int IdVenda { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public Nullable<int> IdFinanceiroTipo { get; set; }
        public Nullable<int> TipoVenda { get; set; }
        public Nullable<int> Pago { get; set; }
        public decimal Valor { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
        public string StatusVenda { get; set; }
        public string Obs { get; set; }

        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<Comissao> Comissao { get; set; }
        public virtual ICollection<Financeiro> Financeiro { get; set; }
        public virtual ICollection<ProdutosVenda> ProdutosVenda { get; set; }
        public virtual ICollection<NotaPromissoria> NotaPromissoria { get; set; }
    }
}
