//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_BookStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comissao
    {
        public int idComissao { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
        public Nullable<System.DateTime> DataBaixa { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> ValorComissao { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
