//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JC_BookStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceiroTipo
    {
        public FinanceiroTipo()
        {
            this.Financeiro = new HashSet<Financeiro>();
        }
    
        public int IdFinanceiroTipo { get; set; }
        [Required]
        public string FinanceiroTipoDesc { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual ICollection<Financeiro> Financeiro { get; set; }
    }
}
