//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JC_BookStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int idFuncionario { get; set; }
        public Nullable<int> IdFuncao { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string CEP { get; set; }
        [Required]
        public string Endereco { get; set; }
        [Required]
        public string Bairro { get; set; }
        [Required]
        public Nullable<short> Cidade { get; set; }
        [Required]
        public Nullable<short> Estado { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Nascimento { get; set; }
        [Required]
        [CustomValidation.CustomValidationCpf(ErrorMessage = "CPF inválido")]
        public string CPF { get; set; }
        [Required]
        public string RG { get; set; }
        [DataType(DataType.EmailAddress)]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
        public string Email { get; set; }
        [Required]
        public string Telefone { get; set; }
        [Required]
        public string Celular { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DataDemissao { get; set; }
        [Required]
        public Nullable<decimal> Salario { get; set; }
        [Required]
        public Nullable<int> DiaPagamento { get; set; }
        public Nullable<int> Comissao { get; set; }
        public string Observacao { get; set; }
    
        public virtual Funcao Funcao { get; set; }
    }
}
