//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JC_BookStation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public Produtos()
        {
            this.ProdutosCompra = new HashSet<ProdutosCompra>();
            this.ProdutosOrcamento = new HashSet<ProdutosOrcamento>();
            this.ProdutosVenda = new HashSet<ProdutosVenda>();
            this.Arquivo1 = new HashSet<Arquivo>();
        }
    
        public int IdProduto { get; set; }
        [Required]
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Nomecupom { get; set; }
        [Required]
        public Nullable<decimal> ValorVenda { get; set; }
        [Required]
        public Nullable<decimal> ValorCompra { get; set; }
        [Required]
        public Nullable<int> Lucro { get; set; }
        [Required]
        public Nullable<int> Estoque { get; set; }
        public Nullable<decimal> ValorPrazo { get; set; }
        [Required]
        public Nullable<int> EstoqueMinimo { get; set; }
        public string Observacao { get; set; }
        [Required]
        public Nullable<long> CodigoBarras { get; set; }
        public string UnCompra { get; set; }
        public string UnVenda { get; set; }
        public Nullable<int> Fator { get; set; }
        [Required(ErrorMessage = "O valor do BONUS deve ser informado.!")]
        public Nullable<decimal> Comissao { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public bool AtivaSite { get; set; }
        public string NomeFoto { get; set; }
        [Required]
        public Nullable<int> IdFornecedor { get; set; }
    
        public virtual GrupoProdutos GrupoProdutos { get; set; }
        public virtual ICollection<ProdutosCompra> ProdutosCompra { get; set; }
        public virtual ICollection<ProdutosOrcamento> ProdutosOrcamento { get; set; }
        public virtual ICollection<ProdutosVenda> ProdutosVenda { get; set; }
        public virtual Arquivo Arquivo { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual ICollection<Arquivo> Arquivo1 { get; set; }
    }
}
